spring:
  application:
    name: library-events-producer-v2
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 10
        batch.size: 32768
    topic:
      name: library-events
      partitions: 3
      replication-factor: 1

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.learnjava.library_events_producer_v2: DEBUG
    org.springframework.web: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

kafka:
  topic:
    name: library-events
